xcodeproj 'Xmas.xcodeproj'
platform :ios, '7.0'

pod 'AeroGear', :git => 'https://github.com/cvasilak/aerogear-ios.git', :branch => 'AGIOS-181'
pod 'AeroGear-Crypto', :git => 'https://github.com/cvasilak/aerogear-crypto-ios.git', :branch => 'error'
